# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/course_registration?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= mysqlroot12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=AcademiaPro

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080